### ISSUE TITLE
add viewport 2.0 support  and proper backward compat

### ISSUE THREAD

**Issue by redpawfx** [redpawfx/partio#40]
maya 2015's viewport defaults to using viewport 2.0 now.  
and it has many improvements for displaying large particle clouds 
take advantage of this and support it.

**Comment by ruchitinfushion** [comment]
Maya 2016 VP2.0 update ??

**Comment by redpawfx** [comment]
Latest Commits  support  VP2  now,   Partio Instancer still does not  support it yet, for point draw, but  its a minor  issue.
